---
repos:
  - repo: https://github.com/python/black.git
    rev: 22.10.0
    hooks:
      - id: black
        name: black (python3)
        language_version: python3
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python3)
        language_version: python3
        args: ["--check", "--profile=black"]
  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
    -   id: flake8
