---
repos:
  - repo: https://github.com/python/black.git
    rev: 22.3.0
    hooks:
      - id: black
        name: black (python3)
        language_version: python3
        args: ["--check"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python3)
        language_version: python3
        args: ["--check", "--profile=black"]
